# Generated by Django 2.2.10 on 2020-07-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanukai', '0006_uploadedimage_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='private',
            new_name='private_image',
        ),
    ]
