version: "3.4"
services:
  image_search_python:
    restart: always
    build:
      context: ./
      dockerfile: "python-dockerfile"
    environment:
      - "PYTHONUNBUFFERED=1"
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - .:/app
      - ./var/.keras:/root/.keras
    networks:
      - image_search
  image_search_nginx:
    restart: always
    build: ./nginx
    ports:
      - "${DOCKER_WEB_PORT}:80"
      - "${DOCKER_WEB_SSL_PORT}:443"
    volumes:
      - .:/app
#      - /media/kkosinski/linux1/images:/app/static/images
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - image_search_python
      - image_search_node
    networks:
      - image_search
  image_search_milvus:
    image: milvusdb/milvus:0.9.0-cpu-d051520-cb92b1
    volumes:
      - ./var/milvus/db:/var/lib/milvus/db
      - ./milvus_config:/var/lib/milvus/conf
      - ./var/milvus/logs:/var/lib/milvus/logs
      - ./var/milvus/wal:/var/lib/milvus/wal
    ports:
      - 19530
      - 19121
      - 9091
    networks:
      - image_search
    depends_on:
      - image_search_python
  image_search_elastic:
    restart: always
    ports:
      - 9200
    image: docker.elastic.co/elasticsearch/elasticsearch:${DOCKER_ELASTICSEARCH_VERSION}
    volumes:
      - ./var/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - image_search
    depends_on:
      - image_search_python
  image_search_node:
    build:
      context: ./
      dockerfile: node-dockerfile
    working_dir: /app
    #command: /bin/sh -c "npm install ; npm start"
    ports:
      - "${NODEJS_PORT}"
    volumes:
      - .:/app
    networks:
      - image_search
  image_search_redis:
    restart: always
    ports:
      - 6379
    image: redis:latest
    networks:
      - image_search
    volumes:
      - ./var/redis:/data
networks:
  image_search:
    driver: "bridge"
