version: "3.4"
services:
  image_search_python:
    restart: always
    build:
      context: ./
      dockerfile: "dockerfile/python-dockerfile-prod"
    environment:
      - "PYTHONUNBUFFERED=1"
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - .:/app
      - ./var/.keras:/root/.keras
    networks:
      - image_search
  image_search_nginx:
    restart: always
    build: ./nginx
    ports:
      - "${DOCKER_WEB_PORT}:80"
      - "${DOCKER_WEB_SSL_PORT}:443"
    volumes:
      - .:/app
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - image_search_python
      - image_search_node
    networks:
      - image_search
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; certbot renew; nginx -s reload; done & nginx -g \"daemon off;\"'"
  image_search_milvus:
    image: milvusdb/milvus:0.9.0-cpu-d051520-cb92b1
    volumes:
      - ./var/milvus/db:/var/lib/milvus/db
      - ./milvus_config:/var/lib/milvus/conf
      - ./var/milvus/logs:/var/lib/milvus/logs
      - ./var/milvus/wal:/var/lib/milvus/wal
    networks:
      - image_search
    depends_on:
      - image_search_python
  image_search_elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:${DOCKER_ELASTICSEARCH_VERSION}
    volumes:
      - ./var/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - image_search
    depends_on:
      - image_search_python
  image_search_node:
    build:
      context: ./
      dockerfile: dockerfile/node-dockerfile
    working_dir: /app
    ports:
      - "${NODEJS_PORT}"
    volumes:
      - .:/app
    networks:
      - image_search
  image_search_mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - image_search
  image_search_redis:
    restart: always
    image: redis:latest
    networks:
      - image_search
    volumes:
      - ./var/redis:/data
  image_search_tensorflow_serving:
    restart: always
    image: tensorflow/serving
    networks:
      - image_search
    volumes:
      - ./tanukai_model:/models/tanukai_model/1
    environment:
      - "MODEL_NAME=tanukai_model"
networks:
  image_search:
    driver: "bridge"
