export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const SEARCH_RESET = "SEARCH_RESET";

export const DATABASE_SEARCH_START = "DATABASE_SEARCH_START";
export const DATABASE_SEARCH_SUCCESS = "DATABASE_SEARCH_SUCCESS";
export const DATABASE_SEARCH_FAILED = "DATABASE_SEARCH_FAILED";

export const UPLOADED_SEARCH_START = "UPLOADED_SEARCH_START";
export const UPLOADED_SEARCH_SUCCESS = "UPLOADED_SEARCH_SUCCESS";
export const UPLOADED_SEARCH_FAILED = "UPLOADED_SEARCH_FAILED";

export const GET_SETTINGS_START = "GET_SETTINGS_START";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILED = "GET_SETTINGS_FAILED";

export const PUT_PARTITIONS_START = "PUT_PARTITIONS_START";
export const PUT_PARTITIONS_SUCCESS = "PUT_PARTITIONS_SUCCESS";
export const PUT_PARTITIONS_FAILED = "PUT_PARTITIONS_FAILED";

export const PUT_RATING_START = "PUT_RATING_START";
export const PUT_RATING_SUCCESS = "PUT_RATING_SUCCESS";
export const PUT_RATING_FAILED = "PUT_RATING_FAILED";

export const IMAGE_URL_SEARCH_START = "IMAGE_URL_SEARCH_START";
export const IMAGE_URL_SEARCH_SUCCESS = "IMAGE_URL_SEARCH_SUCCESS";
export const IMAGE_URL_SEARCH_FAILED = "IMAGE_URL_SEARCH_FAILED";
