import os

import requests
from PIL.Image import Image
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.densenet import preprocess_input
import numpy as np
import tensorflow as tf
import config

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"  # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# os.environ["CUDA_VISIBLE_DEVICES"] = ""

gpu_devices = tf.config.experimental.list_physical_devices('GPU')
if gpu_devices:
    tf.config.experimental.set_memory_growth(gpu_devices[0], True)  # Limit the GPU memory usage


class FeatureExtractor:
    """
    Extracts image features using a CNN
    """

    IMG_WIDTH = 224
    IMG_HEIGHT = 224

    def get_features(self, img: Image) -> np.ndarray:
        """
        Returns a numpy array of normalized image features generated by the avg_pool layer of
        the CNN
        :param img: Pillow Image
        :return: (1, 1024) numpy array
        """
        predictions = self._extract_predictions(img)
        normalized_features = predictions / np.linalg.norm(predictions)
        return normalized_features

    def _extract_predictions(self, img: Image) -> list:
        img = img.resize((self.IMG_HEIGHT, self.IMG_HEIGHT))
        img = img.convert('RGB')
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x).tolist()
        response = requests.post(
            f'{config.TENSORFLOW_SERVING_MODEL_ADDRESS}:predict',
            json={'instances': x}
        )
        json_response = response.json()
        return json_response.get('predictions')
