# Generated by Django 2.2.10 on 2020-07-16 16:17

from django.db import migrations, models
import tanukai_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tanukai_api", "0004_auto_20200714_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(
                max_length=500,
                upload_to="uploaded/",
                validators=[tanukai_api.validators.validate_max_image_size],
            ),
        ),
    ]
