# Generated by Django 2.2.10 on 2020-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tanukai_api", "0005_auto_20200716_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
